image: ubuntu
pipelines:
  branches:
    uat-marketplace:
      - step:
          name: Build and Test
#          size: 2x
          script:
            - IMAGE_NAME=marketplace
            - docker build . --file Dockerfile --tag techbazaar/uat-marketplace:latest
            - echo ${DOCKERHUB_PASSWORD} | docker login --username $DOCKERHUB_USERNAME --password-stdin
            - docker push techbazaar/uat-marketplace:latest 
            - docker tag techbazaar/uat-marketplace:latest techbazaar/uat-marketplace:$BITBUCKET_COMMIT             
            - docker push techbazaar/uat-marketplace:$BITBUCKET_COMMIT
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: $USER
                SERVER: $SERVER
                COMMAND: 'bash /root/docker-compose/uat-marketplace/uat-marketplace.sh'
          services:
            - docker 
definitions:
  services:
    docker:
      memory: 3070
