import Head from 'next/head'
import Banner from '@/sections/Home/Banner'
import RecomendedProducts from '@/sections/Home/RecomendedProducts'
import FeaturedCategories from '@/sections/Home/FeaturedCategories'
import Brands from '@/sections/Home/Brands'
import TopSellers from '@/sections/Home/TopSellers'
import { Layout } from "../components/index"

export default function Home() {
  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main >
          <Banner />
          <RecomendedProducts />
          <TopSellers />
          <FeaturedCategories />
          <Brands />
        </main>
      </Layout>
    </>
  )
}
